export const categories = [
  "Kue Tradisional",
  "Cake & Bakery",
  "Gurih & Siap Makan",
] as const;

export type Category = (typeof categories)[number];

export type MenuItem = {
  id: string;
  name: string;
  category: Category;
  description: string;
  price?: string;
  image?: string;
  featured?: boolean;
};

export const menuItems: MenuItem[] = [
  {
    id: "pie-buah",
    name: "Pie Buah",
    category: "Kue Tradisional",
    description: "Tart mungil dengan topping buah warna-warni.",
    image: "/images/menu/fruit-pies.jpeg",
    featured: true,
  },
  {
    id: "pie-susu",
    name: "Pie Susu",
    category: "Kue Tradisional",
    description: "Pie lembut dengan isian susu yang manis dan creamy.",
    image: "/images/menu/pie-susu.jpeg",
  },
  {
    id: "talam-ubi",
    name: "Talam Ubi",
    category: "Kue Tradisional",
    description: "Kue talam lembut dengan lapisan rasa ubi.",
    image: "/images/menu/talam-ubi.jpeg",
  },
  {
    id: "talam-ijo-gulmer",
    name: "Talam Ijo Gulmer",
    category: "Kue Tradisional",
    description: "Talam hijau manis dengan sentuhan gula merah.",
    image: "/images/menu/talam-ijo.jpeg",
  },
  {
    id: "lumpur-kentang",
    name: "Lumpur Kentang",
    category: "Kue Tradisional",
    description: "Kue lumpur rumahan yang lembut dan wangi.",
  },
  {
    id: "bolu-semangka",
    name: "Bolu Semangka",
    category: "Kue Tradisional",
    description: "Bolu kukus ceria dengan warna semangka.",
    image: "/images/menu/bolu-semangka.jpeg",
    featured: true,
  },
  {
    id: "waffle",
    name: "Waffle",
    category: "Kue Tradisional",
    description: "Tersedia rasa coklat atau keju.",
  },
  {
    id: "kue-ijo-lumpang",
    name: "Kue Ijo (Lumpang)",
    category: "Kue Tradisional",
    description: "Kue hijau legit dengan kelapa parut.",
    image: "/images/menu/kue-lumpang.jpeg",
  },
  {
    id: "kue-pisang",
    name: "Kue Pisang",
    category: "Kue Tradisional",
    description: "Camilan pisang manis, cocok untuk teman minum teh.",
  },
  {
    id: "bolu-kukus",
    name: "Bolu Kukus",
    category: "Kue Tradisional",
    description: "Bolu kukus mekar dalam pilihan warna yang ceria.",
    image: "/images/menu/bolu-kukus.jpeg",
  },
  {
    id: "kue-pepe-coklat",
    name: "Kue Pepe Coklat",
    category: "Kue Tradisional",
    description: "Kue lapis kenyal dengan rasa coklat.",
    image: "/images/menu/kue-pepe.jpeg",
  },
  {
    id: "talam-lapis-pandan-suji",
    name: "Kue Talam Lapis Pandan Suji",
    category: "Kue Tradisional",
    description: "Lapisan pandan suji yang wangi dan lembut.",
    image: "/images/menu/talam-ijo.jpeg",
  },
  {
    id: "kue-soes",
    name: "Kue Soes",
    category: "Kue Tradisional",
    description: "Soes mungil untuk camilan dan isi hampers.",
    image: "/images/menu/kue-soes.jpeg",
  },
  {
    id: "bugis",
    name: "Bugis",
    category: "Kue Tradisional",
    description: "Jajanan ketan lembut berbungkus daun.",
  },
  {
    id: "bugis-mandi",
    name: "Bugis Mandi",
    category: "Kue Tradisional",
    description: "Kue bugis lembut dengan kuah santan manis.",
  },
  {
    id: "bugis-labu-kuning",
    name: "Bugis Labu Kuning",
    category: "Kue Tradisional",
    description: "Kue bugis dengan rasa labu kuning.",
  },
  {
    id: "bugis-ketan-hitam",
    name: "Bugis Ketan Hitam",
    category: "Kue Tradisional",
    description: "Ketan hitam legit dalam balutan daun pisang.",
    image: "/images/menu/bugis-ketan-hitam.jpeg",
  },
  {
    id: "gemblong-ketan",
    name: "Gemblong Ketan",
    category: "Kue Tradisional",
    description: "Camilan ketan kenyal berbalut wijen.",
    image: "/images/menu/gemblong.jpeg",
  },
  {
    id: "kue-pia",
    name: "Kue Pia",
    category: "Kue Tradisional",
    description: "Sopia dengan isian kacang ijo kupas.",
    image: "/images/menu/kue-pia.jpeg",
  },
  {
    id: "bolu-marmer",
    name: "Bolu Marmer",
    category: "Cake & Bakery",
    description: "Irisan bolu klasik dengan motif marmer coklat.",
    image: "/images/menu/bolu-marmer-banana.jpeg",
  },
  {
    id: "butter-fruit-cake",
    name: "Butter Fruit Cake",
    category: "Cake & Bakery",
    description: "Butter cake dengan potongan buah warna-warni.",
    image: "/images/menu/butter-fruit-cake.jpeg",
  },
  {
    id: "brownies-panggang",
    name: "Brownies Panggang",
    category: "Cake & Bakery",
    description: "Brownies panggang yang padat dan coklaty.",
    image: "/images/menu/brownies.jpeg",
  },
  {
    id: "soft-cookies",
    name: "Soft Cookies",
    category: "Cake & Bakery",
    description: "Cookies lembut dengan chocolate chips.",
    image: "/images/menu/soft-cookies.jpeg",
  },
  {
    id: "bolu-gulung",
    name: "Bolu Gulung",
    category: "Cake & Bakery",
    description: "Bolu gulung lembut dengan motif yang cantik.",
    image: "/images/menu/bolu-gulung.jpeg",
  },
  {
    id: "banana-cake",
    name: "Banana Cake",
    category: "Cake & Bakery",
    description: "Cake pisang rumahan yang harum dan moist.",
    image: "/images/menu/banana-cake.jpeg",
  },
  {
    id: "pisang-molen-lilit",
    name: "Pisang Molen Lilit",
    category: "Cake & Bakery",
    description: "Pisang manis dalam kulit renyah.",
    image: "/images/menu/pisang-molen.jpeg",
  },
  {
    id: "donat-mini",
    name: "Donat Mini",
    category: "Cake & Bakery",
    description: "Donat mini dengan topping seru untuk dibagi-bagi.",
    image: "/images/menu/donat-mini.jpeg",
    featured: true,
  },
  {
    id: "dorayaki",
    name: "Dorayaki",
    category: "Cake & Bakery",
    description: "Dorayaki empuk dengan pilihan rasa isian.",
    image: "/images/menu/dorayaki.jpeg",
  },
  {
    id: "dadar-gulung",
    name: "Dadar Gulung",
    category: "Cake & Bakery",
    description: "Dadar gulung pandan yang manis dan wangi.",
    image: "/images/menu/dadar-gulung.jpeg",
  },
  {
    id: "roti-goreng",
    name: "Roti Goreng",
    category: "Cake & Bakery",
    description: "Roti goreng hangat untuk camilan gurih-manis.",
    image: "/images/menu/roti-goreng.jpeg",
  },
  {
    id: "chiffon-ijo-slice",
    name: "Chiffon Ijo Slice",
    category: "Cake & Bakery",
    description: "Irisan chiffon pandan yang ringan dan lembut.",
    image: "/images/menu/chiffon-ijo.jpeg",
  },
  {
    id: "lemper-ayam",
    name: "Lemper Ayam",
    category: "Gurih & Siap Makan",
    description: "Ketan gurih berisi ayam, dibungkus daun pisang.",
    image: "/images/menu/lemper.jpeg",
  },
  {
    id: "sosis-solo",
    name: "Sosis Solo",
    category: "Gurih & Siap Makan",
    description: "Jajanan klasik berisi ayam berbumbu.",
    image: "/images/menu/risol.jpeg",
  },
  {
    id: "risol-sayur",
    name: "Risol Sayur",
    category: "Gurih & Siap Makan",
    description: "Isian wortel dan kentang.",
    image: "/images/menu/risol.jpeg",
  },
  {
    id: "risol-smoke-beef-telur-mayo",
    name: "Risol Smoke Beef Telur Mayo",
    category: "Gurih & Siap Makan",
    description: "Risol creamy dengan smoke beef, telur, dan mayo.",
    image: "/images/menu/risol.jpeg",
  },
  {
    id: "dimsum-premium",
    name: "Dimsum Premium",
    category: "Gurih & Siap Makan",
    description: "Pilihan tenggiri, ayam, dan udang.",
    image: "/images/menu/siomay.jpeg",
  },
  {
    id: "pastel-telur",
    name: "Pastel Telur",
    category: "Gurih & Siap Makan",
    description: "Pastel renyah dengan isian telur.",
    image: "/images/menu/pastel.jpeg",
  },
  {
    id: "pastel-tanpa-telur",
    name: "Pastel tanpa Telur",
    category: "Gurih & Siap Makan",
    description: "Pastel renyah tanpa isian telur.",
    image: "/images/menu/pastel.jpeg",
  },
  {
    id: "nasi-bakar",
    name: "Nasi Bakar",
    category: "Gurih & Siap Makan",
    description: "Tersedia ayam atau teri, dengan pilihan pedas.",
    image: "/images/menu/nasi-bakar.jpeg",
    featured: true,
  },
  {
    id: "bacang",
    name: "Bacang Nasi / Ketan",
    category: "Gurih & Siap Makan",
    description: "Bacang ayam dalam bungkus daun yang khas.",
    image: "/images/menu/bacang.jpeg",
  },
  {
    id: "siomay-benteng",
    name: "Siomay Benteng",
    category: "Gurih & Siap Makan",
    description: "1 kap isi 4, lengkap saus kacang, kecap, sambal, dan jeruk limau.",
    image: "/images/menu/siomay.jpeg",
  },
  {
    id: "lontong-isi",
    name: "Lontong Isi",
    category: "Gurih & Siap Makan",
    description: "Pilihan isi ayam, sayur, atau oncom.",
    image: "/images/menu/lemper.jpeg",
  },
  {
    id: "choipan",
    name: "Choipan",
    category: "Gurih & Siap Makan",
    description: "Chaikue/kue sayur halal. 1 kap isi 4 lengkap saus merah.",
    image: "/images/menu/siomay.jpeg",
  },
  {
    id: "lumpia-choipan",
    name: "Lumpia Choipan",
    category: "Gurih & Siap Makan",
    description: "Lumpia isi choipan dengan bengkuang dan ebi.",
    image: "/images/menu/lumpia-choipan.jpeg",
  },
];
