export const categories = [
  "Kue Tradisional",
  "Cake & Bakery",
  "Gurih & Siap Makan",
] as const;

export type Category = (typeof categories)[number];

export type MenuItem = {
  id: string;
  name: string;
  category: Category;
  description: string;
  price?: string;
  image?: string;
  featured?: boolean;
};

export const menuItems: MenuItem[] = [
  {
    id: "pie-buah",
    name: "Pie Buah",
    category: "Kue Tradisional",
    description: "Tart mungil dengan topping buah warna-warni.",
    image: "/images/menu/chat/clean/pie-buah.jpg",
    featured: true,
  },
  {
    id: "pie-susu",
    name: "Pie Susu",
    category: "Kue Tradisional",
    description: "Pie lembut dengan isian susu yang manis dan creamy.",
  },
  {
    id: "talam-ubi",
    name: "Talam Ubi",
    category: "Kue Tradisional",
    description: "Kue talam lembut dengan lapisan rasa ubi.",
    image: "/images/menu/talam-ubi.jpeg",
  },
  {
    id: "talam-ijo-gulmer",
    name: "Talam Ijo Gulmer",
    category: "Kue Tradisional",
    description: "Talam hijau manis dengan sentuhan gula merah.",
    image: "/images/menu/chat/clean/talam-ijo-gulmer.jpg",
  },
  {
    id: "lumpur-kentang",
    name: "Lumpur Kentang",
    category: "Kue Tradisional",
    description: "Kue lumpur rumahan yang lembut dan wangi.",
    image: "/images/menu/chat/clean/kue-lumpur-kentang.jpg",
  },
  {
    id: "bolu-semangka",
    name: "Bolu Semangka",
    category: "Kue Tradisional",
    description: "Bolu kukus ceria dengan warna semangka.",
    image: "/images/menu/bolu-semangka.jpeg",
    featured: true,
  },
  {
    id: "waffle",
    name: "Waffle",
    category: "Kue Tradisional",
    description: "Tersedia rasa coklat atau keju.",
    image: "/images/menu/chat/clean/waffle.jpg",
  },
  {
    id: "kue-ijo-lumpang",
    name: "Kue Ijo (Lumpang)",
    category: "Kue Tradisional",
    description: "Kue hijau legit dengan kelapa parut.",
    image: "/images/menu/chat/clean/kue-lumpang.jpg",
  },
  {
    id: "kue-pisang",
    name: "Kue Pisang",
    category: "Kue Tradisional",
    description: "Camilan pisang manis, cocok untuk teman minum teh.",
    image: "/images/menu/chat/clean/kue-pisang.jpg",
  },
  {
    id: "bolu-kukus",
    name: "Bolu Kukus",
    category: "Kue Tradisional",
    description: "Bolu kukus mekar dalam pilihan warna yang ceria.",
    image: "/images/menu/chat/bolu-kukus.jpg",
  },
  {
    id: "kue-pepe-coklat",
    name: "Kue Pepe Coklat",
    category: "Kue Tradisional",
    description: "Kue lapis kenyal dengan rasa coklat.",
    image: "/images/menu/chat/clean/kue-pepe-coklat.jpg",
  },
  {
    id: "talam-lapis-pandan-suji",
    name: "Lapis Tepung Beras Suji",
    category: "Kue Tradisional",
    description: "Kue lapis pandan suji yang wangi, lembut, dan kenyal.",
    image: "/images/menu/chat/clean/lapis-tepung-beras-suji.jpg",
  },
  {
    id: "kue-soes",
    name: "Kue Soes",
    category: "Kue Tradisional",
    description: "Soes mungil untuk camilan dan isi hampers.",
    image: "/images/menu/chat/clean/kue-soes.jpg",
  },
  {
    id: "bugis",
    name: "Bugis",
    category: "Kue Tradisional",
    description: "Kue bugis suji dengan isi unti kelapa manis.",
    image: "/images/menu/chat/clean/bugis.jpg",
  },
  {
    id: "bugis-mandi",
    name: "Bugis Mandi",
    category: "Kue Tradisional",
    description: "Kue bugis lembut dengan kuah santan manis.",
    image: "/images/menu/chat/clean/bugis-mandi-latest.jpg",
  },
  {
    id: "bugis-labu-kuning",
    name: "Bugis Labu Kuning",
    category: "Kue Tradisional",
    description: "Kue bugis labu kuning dengan isi unti kelapa.",
    image: "/images/menu/chat/bugis-labu.jpg",
  },
  {
    id: "bugis-ketan-hitam",
    name: "Bugis Ketan Hitam",
    category: "Kue Tradisional",
    description: "Ketan hitam legit dalam balutan daun pisang.",
    image: "/images/menu/chat/clean/bugis-ketan-hitam.jpg",
  },
  {
    id: "gemblong-ketan",
    name: "Gemblong Ketan",
    category: "Kue Tradisional",
    description: "Camilan ketan kenyal berbalut wijen.",
    image: "/images/menu/chat/clean/gemblong-ketan.jpg",
  },
  {
    id: "kue-pia",
    name: "Kue Pia",
    category: "Kue Tradisional",
    description: "Sopia dengan isian kacang ijo kupas.",
    image: "/images/menu/chat/clean/kue-pia.jpg",
  },
  {
    id: "bolu-marmer",
    name: "Bolu Marmer",
    category: "Cake & Bakery",
    description: "Irisan bolu klasik dengan motif marmer coklat.",
    image: "/images/menu/bolu-marmer-banana.jpeg",
  },
  {
    id: "butter-fruit-cake",
    name: "Butter Fruit Cake",
    category: "Cake & Bakery",
    description: "Butter cake dengan potongan buah warna-warni.",
    image: "/images/menu/chat/clean/butter-fruit-cake.jpg",
  },
  {
    id: "brownies-panggang",
    name: "Brownies Panggang",
    category: "Cake & Bakery",
    description: "Brownies panggang yang padat dan coklaty.",
    image: "/images/menu/chat/clean/brownies-chat.jpg",
  },
  {
    id: "soft-cookies",
    name: "Soft Cookies",
    category: "Cake & Bakery",
    description: "Cookies lembut dengan chocolate chips.",
    image: "/images/menu/chat/clean/soft-cookies.jpg",
  },
  {
    id: "bolu-gulung",
    name: "Bolu Gulung",
    category: "Cake & Bakery",
    description: "Bolu gulung lembut dengan motif yang cantik.",
    image: "/images/menu/chat/clean/bolu-gulung.jpg",
  },
  {
    id: "banana-cake",
    name: "Banana Cake",
    category: "Cake & Bakery",
    description: "Cake pisang rumahan yang harum dan moist.",
    image: "/images/menu/banana-cake.jpeg",
  },
  {
    id: "pisang-molen-lilit",
    name: "Pisang Molen Lilit",
    category: "Cake & Bakery",
    description: "Pisang manis dalam kulit renyah.",
  },
  {
    id: "donat-mini",
    name: "Donat Mini",
    category: "Cake & Bakery",
    description: "Donat mini dengan topping seru untuk dibagi-bagi.",
    image: "/images/menu/chat/clean/donat-mini.jpg",
    featured: true,
  },
  {
    id: "dorayaki",
    name: "Dorayaki",
    category: "Cake & Bakery",
    description: "Dorayaki empuk dengan pilihan rasa isian.",
    image: "/images/menu/chat/clean/dorayaki.jpg",
  },
  {
    id: "dadar-gulung",
    name: "Dadar Gulung",
    category: "Cake & Bakery",
    description: "Dadar gulung pandan yang manis dan wangi.",
    image: "/images/menu/chat/dadar-gulung.jpg",
  },
  {
    id: "roti-goreng",
    name: "Roti Goreng",
    category: "Cake & Bakery",
    description: "Roti goreng dengan pilihan isian coklat, ayam, atau coklat keju.",
    image: "/images/menu/chat/roti-goreng-2026-08-20.jpg",
  },
  {
    id: "chiffon-ijo-slice",
    name: "Chiffon Ijo Slice",
    category: "Cake & Bakery",
    description: "Irisan chiffon pandan yang ringan dan lembut.",
    image: "/images/menu/chat/clean/chiffon-ijo.jpg",
  },
  {
    id: "lemper-ayam",
    name: "Lemper Ayam",
    category: "Gurih & Siap Makan",
    description: "Ketan gurih berisi ayam, dibungkus daun pisang.",
    image: "/images/menu/chat/lemper-ayam-bakar-ongol-ongol.jpg",
  },
  {
    id: "sosis-solo",
    name: "Sosis Solo",
    category: "Gurih & Siap Makan",
    description: "Jajanan klasik berisi ayam berbumbu.",
    image: "/images/menu/chat/clean/sosis-solo.jpg",
  },
  {
    id: "risol-sayur",
    name: "Risol Sayur",
    category: "Gurih & Siap Makan",
    description: "Isian wortel dan kentang.",
    image: "/images/menu/chat/risol-sayur.jpg",
  },
  {
    id: "risol-smoke-beef-telur-mayo",
    name: "Risol Smoke Beef Telur Mayo",
    category: "Gurih & Siap Makan",
    description: "Risol creamy dengan smoke beef, telur, dan mayo.",
    image: "/images/menu/chat/clean/risol-smoke-beef.jpg",
  },
  {
    id: "dimsum-premium",
    name: "Dimsum Premium",
    category: "Gurih & Siap Makan",
    description: "Pilihan tenggiri, ayam, dan udang.",
    image: "/images/menu/chat/clean/dimsum-premium.jpg",
  },
  {
    id: "pastel-telur",
    name: "Pastel Telur",
    category: "Gurih & Siap Makan",
    description: "Pastel renyah dengan isian telur.",
    image: "/images/menu/pastel.jpeg",
  },
  {
    id: "pastel-tanpa-telur",
    name: "Pastel tanpa Telur",
    category: "Gurih & Siap Makan",
    description: "Pastel renyah tanpa isian telur.",
    image: "/images/menu/chat/clean/pastel-tanpa-telur.jpg",
  },
  {
    id: "nasi-bakar",
    name: "Nasi Bakar",
    category: "Gurih & Siap Makan",
    description: "Tersedia ayam atau teri, dengan pilihan pedas.",
    image: "/images/menu/nasi-bakar.jpeg",
    featured: true,
  },
  {
    id: "bacang",
    name: "Bacang Nasi / Ketan",
    category: "Gurih & Siap Makan",
    description: "Bacang ayam dalam bungkus daun yang khas.",
    image: "/images/menu/chat/clean/bacang.jpg",
  },
  {
    id: "siomay-benteng",
    name: "Siomay Benteng",
    category: "Gurih & Siap Makan",
    description: "1 kap isi 4, lengkap saus kacang, kecap, sambal, dan jeruk limau.",
    image: "/images/menu/chat/clean/siomay-benteng.jpg",
  },
  {
    id: "lontong-isi",
    name: "Lontong Isi",
    category: "Gurih & Siap Makan",
    description: "Pilihan isi ayam, sayur, atau oncom.",
    image: "/images/menu/chat/lontong-isi.jpg",
  },
  {
    id: "choipan",
    name: "Choipan",
    category: "Gurih & Siap Makan",
    description: "Chaikue/kue sayur halal. 1 kap isi 4 lengkap saus merah.",
    image: "/images/menu/chat/choipan.jpg",
  },
  {
    id: "lumpia-choipan",
    name: "Lumpia Choipan",
    category: "Gurih & Siap Makan",
    description: "Lumpia isi choipan dengan bengkuang dan ebi.",
    image: "/images/menu/chat/choipan.jpg",
  },
  {
    id: "nasi-uduk-wangi",
    name: "Nasi Uduk Wangi",
    category: "Gurih & Siap Makan",
    description: "Nasi uduk dengan bihun, mie, kering tempe, telur, sambal terasi, dan bawang goreng.",
    image: "/images/menu/chat/clean/nasi-uduk-wangi.jpg",
    featured: true,
  },
  {
    id: "kue-putu-ayu",
    name: "Kue Putu Ayu",
    category: "Kue Tradisional",
    description: "Kue pandan lembut dengan kelapa parut gurih.",
    image: "/images/menu/chat/clean/putu-ayu.jpg",
  },
  {
    id: "susu-kacang-kedelai",
    name: "Susu Kacang Kedelai",
    category: "Kue Tradisional",
    description: "Minuman kedelai lembut dan menyegarkan.",
    image: "/images/menu/chat/clean/susu-kacang-kedelai.jpg",
  },
  {
    id: "kue-pukis",
    name: "Kue Pukis",
    category: "Cake & Bakery",
    description: "Pukis lembut dengan pilihan topping random yang seru.",
    image: "/images/menu/chat/kue-pukis.jpg",
    featured: true,
  },
  {
    id: "apem-kalimantan",
    name: "Apem Kalimantan (Pa Thong Ko)",
    category: "Kue Tradisional",
    description: "Apem khas Kalimantan dengan tekstur lembut dan aroma wangi.",
    image: "/images/menu/chat/apem-kalimantan.jpg",
  },
  {
    id: "nagasari",
    name: "Nagasari",
    category: "Kue Tradisional",
    description: "Kue pisang lembut dalam bungkus daun, ukuran besar.",
    image: "/images/menu/chat/nagasari.jpg",
  },
  {
    id: "wajik-ketan-gula-merah",
    name: "Wajik Ketan Gula Merah",
    category: "Kue Tradisional",
    description: "Ketan manis legit dengan gula merah.",
    image: "/images/menu/chat/wajik-ketan-gula-merah.jpg",
  },
  {
    id: "onde-macho",
    name: "Onde Macho",
    category: "Kue Tradisional",
    description: "Camilan ketan dengan isian kacang hijau kupas.",
    image: "/images/menu/chat/clean/onde-macho.jpg",
  },
  {
    id: "bubur-singkong-mutiara",
    name: "Bubur Singkong Mutiara",
    category: "Kue Tradisional",
    description: "Bubur singkong manis dengan mutiara yang kenyal.",
    image: "/images/menu/chat/clean/bubur-singkong-mutiara.jpg",
  },
  {
    id: "singkong-thailand",
    name: "Singkong Thailand",
    category: "Kue Tradisional",
    description: "Singkong empuk dengan vla gurih dan taburan keju.",
    image: "/images/menu/chat/clean/singkong-thailand.jpg",
  },
  {
    id: "bolu-tape-keju",
    name: "Bolu Tape Keju",
    category: "Cake & Bakery",
    description: "Bolu tape lembut dengan topping keju.",
    image: "/images/menu/chat/clean/bolu-tape-keju.jpg",
  },
  {
    id: "bolu-pisang-coklat",
    name: "Bolu Pisang Coklat",
    category: "Cake & Bakery",
    description: "Bolu pisang moist dengan sentuhan coklat.",
    image: "/images/menu/chat/clean/bolu-pisang-coklat.jpg",
  },
  {
    id: "donat-kampoeng",
    name: "Donat Kampoeng",
    category: "Cake & Bakery",
    description: "Donat kampung dengan pilihan meses atau icing sugar.",
    image: "/images/menu/chat/clean/donat-kampoeng.jpg",
  },
  {
    id: "aneka-pao",
    name: "Aneka Pao",
    category: "Cake & Bakery",
    description: "Pao dengan pilihan coklat, coklat-kacang kelapa, atau kacang hijau.",
    image: "/images/menu/chat/clean/aneka-pao.jpg",
  },
  {
    id: "burger-homemade",
    name: "Burger Homemade Bun",
    category: "Cake & Bakery",
    description: "Burger bun rumahan dengan isian sosis atau ham.",
    image: "/images/menu/chat/clean/burger-homemade.jpg",
  },
  {
    id: "otak-otak-tenggiri",
    name: "Otak-Otak Tenggiri Mungil",
    category: "Gurih & Siap Makan",
    description: "Otak-otak tenggiri mungil yang gurih.",
    image: "/images/menu/chat/clean/otak-otak-tenggiri.jpg",
  },
  {
    id: "hekeng-ngo-hiong",
    name: "Hekeng / Ngo Hiong Ayam Udang",
    category: "Gurih & Siap Makan",
    description: "Olahan ayam dan udang berbumbu ngo hiong.",
    image: "/images/menu/chat/clean/hekeng-ngo-hiong.jpg",
  },
  {
    id: "semar-mendem",
    name: "Semar Mendem",
    category: "Gurih & Siap Makan",
    description: "Ketan isi ayam yang diselimuti telur dadar.",
    image: "/images/menu/chat/clean/semar-mendem.jpg",
  },
  {
    id: "sushi-aneka-isi",
    name: "Sushi Aneka Isi",
    category: "Gurih & Siap Makan",
    description: "Sushi homemade dengan pilihan isian yang beragam.",
    image: "/images/menu/chat/clean/sushi-aneka-isi.jpg",
  },
  {
    id: "nasi-kepal-jepang",
    name: "Nasi Kepal ala Jepang",
    category: "Gurih & Siap Makan",
    description: "Nasi kepal ala Jepang dengan aneka isian.",
    image: "/images/menu/chat/clean/nasi-kepal-jepang.jpg",
  },
  {
    id: "ketan-urap-serundeng",
    name: "Ketan Urap / Ketan Serundeng",
    category: "Gurih & Siap Makan",
    description: "Ketan gurih dengan pilihan urap atau serundeng.",
    image: "/images/menu/chat/clean/ketan-urap-serundeng.jpg",
  },
  {
    id: "ketan-grintul-kacang-tolo",
    name: "Ketan Grintul Kacang Tolo",
    category: "Gurih & Siap Makan",
    description: "Ketan grintul dengan kacang tolo dan bumbu gurih.",
    image: "/images/menu/chat/ketan-grintul-kacang-tolo.jpg",
  },
  {
    id: "ayam-goreng-lengkuas",
    name: "Ayam Goreng Lengkuas",
    category: "Gurih & Siap Makan",
    description: "Ayam goreng berbumbu lengkuas dengan kremesan gurih.",
    image: "/images/menu/chat/ayam-goreng-lengkuas.jpg",
    featured: true,
  },
  {
    id: "kerupuk-ikan-palembang",
    name: "Kerupuk Ikan Palembang",
    category: "Gurih & Siap Makan",
    description: "Kerupuk ikan khas Palembang yang renyah.",
    image: "/images/menu/chat/clean/kerupuk-ikan-palembang.jpg",
  },
  {
    id: "keripik-kentang-ebi",
    name: "Keripik Kentang Ebi",
    category: "Gurih & Siap Makan",
    description: "Keripik kentang renyah dengan rasa ebi gurih.",
    image: "/images/menu/chat/clean/keripik-kentang-ebi.jpg",
  },
  {
    id: "pempek-dos",
    name: "Pempek DOS",
    category: "Gurih & Siap Makan",
    description: "Satu bungkus berisi 9 pcs pempek DOS.",
    image: "/images/menu/chat/clean/pempek-dos.jpg",
  },
  {
    id: "risol-sosis-keju-mayo",
    name: "Risol Sosis Keju Mayo",
    category: "Gurih & Siap Makan",
    description: "Risol dengan isian sosis, keju, dan mayo.",
    image: "/images/menu/chat/clean/risol-sosis-keju-mayo.jpg",
  },
  {
    id: "kroket-ayam",
    name: "Kroket Isi Wortel Ayam",
    category: "Gurih & Siap Makan",
    description: "Kroket lembut berisi wortel dan ayam.",
    image: "/images/menu/chat/clean/kroket.jpg",
  },
];
